name: 'Format version'
description: 'Format version'
inputs:
  style-as-release:
    description: "true/false flag to format version in release style (yyyy.MM.dd.hh.mm-hash) or as branch reference"
    required: true
outputs:
  version:
    description: Version number of the image released to ECR
    value: ${{ steps.format-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: format-version
      name: "Format version"
      shell: bash
      run: |
        set -eu
        
        IS_RELEASE_STYLE='${{ inputs.style-as-release }}'
        
        dateVersion=$(date +"%Y.%m.%d.%H.%M")-$(echo $GITHUB_SHA | cut -c 1-7) ;
        if [ "$IS_RELEASE_STYLE" = "true" ] ; then
          tag="${dateVersion}" ;
        else
          REF_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
          tag=$(echo ${REF_NAME} | cut -c 1-20 | tr / -)-SNAPSHOT-${dateVersion} ;
        fi
        echo "Version generated: $tag"
        echo "version=$(echo $tag)" >> $GITHUB_OUTPUT ;
